spring:
  datasource:
    url: jdbc:mysql://localhost:3306/veterinary?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
server:
  port: 8081
  servlet:
    context-path: /api/v1

admin:
  email: admin@mail.ru
  password: qwerty
  role: ADMIN